const KEY="belalShopDataV2";let data=JSON.parse(localStorage.getItem(KEY)||'{"entries":[],"dues":[],"cash":{"opening":0},"settings":{"name":"বেলাল কম্পিউটার সল্যুশন","phone":"","address":"সোনার পাড়া বাজার, জালিয়া পালং, ইনানী, উখিয়া, কক্সবাজার","ownerPhoto":""}}');
const $=id=>document.getElementById(id), money=n=>"৳ "+Number(n||0).toLocaleString("bn-BD"), today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function dateText(d){return new Date(d+"T00:00:00").toLocaleDateString("bn-BD",{day:"numeric",month:"short",year:"numeric"})}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));renderAll()}
function openAdd(type="income"){$("modal").classList.add("show");$("entryForm").reset();$("entryDate").value=today();setType(type)}
function closeModal(){$("modal").classList.remove("show")}
function setType(t){$("entryType").value=t;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.type===t))}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setType(b.dataset.type));
$("entryForm").onsubmit=e=>{e.preventDefault();data.entries.push({id:Date.now(),type:$("entryType").value,title:$("entryTitle").value,customer:$("entryCustomer").value,amount:+$("entryAmount").value,date:$("entryDate").value,note:$("entryNote").value});save();closeModal()};
function openDue(edit=null){$("dueModal").classList.add("show");$("dueForm").reset();$("dueDate").value=today();if(edit){$("dueEditId").value=edit.id;$("dueName").value=edit.name;$("duePhone").value=edit.phone;$("dueAmount").value=edit.amount;$("duePaid").value=0;$("dueDate").value=edit.date;$("dueNote").value=edit.note||""}}
function closeDue(){$("dueModal").classList.remove("show")}
$("dueForm").onsubmit=e=>{e.preventDefault();let id=+$("dueEditId").value, amount=+$("dueAmount").value, paid=+$("duePaid").value;if(id){let d=data.dues.find(x=>x.id===id);if(d){d.amount=Math.max(0,d.amount-paid);d.paid=(d.paid||0)+paid;if(d.amount===0)d.closed=true}}else{data.dues.push({id:Date.now(),name:$("dueName").value,phone:$("duePhone").value,amount:amount,date:$("dueDate").value,note:$("dueNote").value,paid:paid,closed:false})}if(paid>0)data.entries.push({id:Date.now()+1,type:"deposit",title:"বাকি আদায় - "+$("dueName").value,customer:$("dueName").value,amount:paid,date:$("dueDate").value,note:"বাকি থেকে জমা"});save();closeDue()};
function delEntry(id){if(confirm("এই লেনদেনটি মুছে ফেলবেন?")){data.entries=data.entries.filter(x=>x.id!==id);save()}}
function delDue(id){if(confirm("এই বাকি হিসাবটি মুছে ফেলবেন?")){data.dues=data.dues.filter(x=>x.id!==id);save()}}
function itemHTML(x){let cls=x.kind==="income"?"green":x.kind==="expense"?"red":x.kind==="deposit"?"blue":"orange",icon=x.kind==="income"?"💰":x.kind==="expense"?"💸":x.kind==="deposit"?"📥":"👤",del=x.kind==="due"?`<button class="icon-btn" onclick="openDue(data.dues.find(d=>d.id===${x.id}))">জমা</button> <button class="icon-btn" onclick="delDue(${x.id})">মুছুন</button>`:`<button class="icon-btn" onclick="delEntry(${x.id})">মুছুন</button>`;return `<div class="item"><div class="item-left"><div class="dot">${icon}</div><div><h3>${esc(x.title||x.name)}</h3><p>${esc(x.customer||x.phone||"")} • ${dateText(x.date)}</p></div></div><div><div class="money ${cls}">${x.kind==="expense"?"-":"+"}${money(x.amount)}</div>${del}</div></div>`}
function renderDashboard(){let t=today(),inc=sum(data.entries.filter(x=>x.date===t&&x.type==="income")),exp=sum(data.entries.filter(x=>x.date===t&&x.type==="expense")),dep=sum(data.entries.filter(x=>x.date===t&&x.type==="deposit")),due=sum(data.dues.filter(x=>!x.closed));$("todayText").textContent=new Date().toLocaleDateString("bn-BD",{weekday:"long",day:"numeric",month:"long"});$("todayIncome").textContent=money(inc);$("todayExpense").textContent=money(exp);$("todayDeposit").textContent=money(dep);$("totalDue").textContent=money(due);$("todayProfit").textContent=money(inc-exp);$("recentList").innerHTML=combined().slice(0,7).map(itemHTML).join("")||empty()}
function combined(){return [...data.entries.map(x=>({...x,kind:x.type})),...data.dues.filter(x=>!x.closed).map(x=>({...x,title:"বাকি: "+x.name,kind:"due"}))].sort((a,b)=>b.id-a.id)}
function sum(a){return a.reduce((s,x)=>s+x.amount,0)}
function renderTransactions(){let q=($("search").value||"").toLowerCase(),f=$("filterType").value,arr=data.entries.filter(x=>(f==="all"||x.type===f)&&(`${x.title} ${x.customer} ${x.note}`).toLowerCase().includes(q)).sort((a,b)=>b.id-a.id);$("transactionList").innerHTML=arr.map(x=>itemHTML({...x,kind:x.type})).join("")||empty()}
function renderDues(){let arr=data.dues.filter(x=>!x.closed),total=sum(arr);$("duePageTotal").textContent=money(total);$("dueList").innerHTML=arr.sort((a,b)=>b.id-a.id).map(x=>itemHTML({...x,title:"বাকি: "+x.name,kind:"due"})).join("")||empty()}
function renderCash(){let t=today(),inc=sum(data.entries.filter(x=>x.date===t&&x.type==="income")),exp=sum(data.entries.filter(x=>x.date===t&&x.type==="expense")),dep=sum(data.entries.filter(x=>x.date===t&&x.type==="deposit"));$("openingCash").value=data.cash.opening||0;$("cashIncome").textContent=money(inc);$("cashExpense").textContent=money(exp);$("cashDuePaid").textContent=money(dep);$("cashTotal").textContent=money((data.cash.opening||0)+inc+dep-exp)}
function saveOpeningCash(){data.cash.opening=+$("openingCash").value||0;localStorage.setItem(KEY,JSON.stringify(data));renderCash()}
function renderReport(){let m=$("reportMonth").value||today().slice(0,7),arr=data.entries.filter(x=>x.date.startsWith(m)),inc=sum(arr.filter(x=>x.type==="income")),exp=sum(arr.filter(x=>x.type==="expense"));$("monthIncome").textContent=money(inc);$("monthExpense").textContent=money(exp);$("monthProfit").textContent=money(inc-exp);$("monthCount").textContent=arr.length.toLocaleString("bn-BD");$("reportDetails").innerHTML=arr.sort((a,b)=>b.id-a.id).map(x=>itemHTML({...x,kind:x.type})).join("")||empty()}
function backupData(){let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ashik-dokan-hisab-backup-"+today()+".json";a.click();URL.revokeObjectURL(a.href)}
function restoreData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.entries||!d.dues)throw 0;data=d;save();alert("Backup Restore সফল হয়েছে।")}catch{alert("সঠিক backup file দিন।")}};r.readAsText(f)}
function printReport(){window.print()}
function saveSettings(){data.settings.name=$("shopName").value;data.settings.phone=$("shopPhone").value;data.settings.address=$("shopAddressInput").value;data.settings.ownerPhoto=$("ownerPhotoName").value;save();alert("দোকানের তথ্য সেভ হয়েছে।")}
function loadSettings(){$("shopName").value=data.settings.name;$("shopPhone").value=data.settings.phone;$("shopAddressInput").value=data.settings.address;$("ownerPhotoName").value=data.settings.ownerPhoto||"";$("headName").textContent=data.settings.name;$("shopTitle").textContent=data.settings.name;$("shopAddress").textContent=data.settings.address}
function empty(){return "<div class='item'><div><h3>কোনো হিসাব নেই</h3><p>নতুন হিসাব যোগ করুন।</p></div></div>"}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderAll(){loadSettings();renderDashboard();renderTransactions();renderDues();renderCash();renderReport()}
$("reportMonth").value=today().slice(0,7);renderAll();